# Generated by Django 2.2.7 on 2019-12-01 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['first_name']},
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['pub_date']},
        ),
    ]
