# Generated by Django 2.2.7 on 2019-12-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webblog', '0002_auto_20191201_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='about_me',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
