# Generated by Django 2.2.7 on 2019-12-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webblog', '0003_author_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(null=True, upload_to='blog_image/'),
        ),
    ]
