# Generated by Django 2.2.7 on 2019-12-03 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webblog', '0004_blog_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_image',
            field=models.ImageField(null=True, upload_to='author_image/'),
        ),
    ]
